services:
  devops_app:
    image: devops:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - TZ=America/Guayaquil

  loadbalancer:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - devops_app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf